server:
  port: 9080

spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://localhost:5432/jpatest
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging.level:
    org.hibernate.sql: debug
