spring:
  profiles:
    active: dev
  devtools:
    livereload:
      enabled:  true
  jpa:
    database-platform: study.sampledatajpa.config.PostgreSQLConfig
    hibernate:
      ddl-auto: create
    show-sql: false
